# .bashrc
BASHRC_ROOT=$(dirname "$(readlink -n "${BASH_SOURCE[0]}")")

# History Control, ignore spaces & ignore dups
HISTCONTROL=ignoreboth
export HISTCONTROL;

# Make less friendly for non-text inputs
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)";

# Set & Export various environment variables
export BASHRC_ROOT
export DOTFILES_ROOT=$(dirname "$BASHRC_ROOT")
export LANG="en_US.UTF-8"
export LC_COLLATE="C"
export PAGER="less"
export EDITOR="vim"
export LESSCHARSET="utf-8"

export WORKON_HOME=$HOME/.virtualenvs

export JAVA_HOME=$(/usr/libexec/java_home)

shopt -s cdspell # correct minor directory spelling errors in cd cmd.
shopt -s checkwinsize # Refresh window size after each cmd
shopt -s cmdhist # save all lines of multi-line cmds to same histry entry
# shopt -s dirspell # correct minor dir spelling errors during completion
shopt -s histappend # append to history file instead of overwrite


# Initialize the prompt command var.
# We'll export this later, but we may want to append to it elsewhere.
PROMPT_COMMAND=''


# Source the .inputrc file if it exists
[ -f $BASHRC_ROOT/inputrc ] && source $BASHRC_ROOT/inputrc

# Source our functions file
[ -f $BASHRC_ROOT/functions.bash ] && source $BASHRC_ROOT/functions.bash

# Source color definitions
[ -f $BASHRC_ROOT/colors.bash ] && source $BASHRC_ROOT/colors.bash

# Include aliases bashrc file
[ -f $BASHRC_ROOT/aliases.bash ] && source $BASHRC_ROOT/aliases.bash

# Source the virtualenvwrapper file
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# Set up our prompt
PS1="\h:\W${GREEN}\$(__git_ps1 ':%s')${RESET}\$ ";

# Include OS Specific bashrc file.
OS_FILE=`uname -s`".bash"
[ -f $BASHRC_ROOT/os/$OS_FILE ] && source $BASHRC_ROOT/os/$OS_FILE

# Include Machine Specific bashrc file
NODE_FILE=`uname -n`".bash"
[ -f $BASHRC_ROOT/machine/$NODE_FILE ] &&
	source $BASHRC_ROOT/machine/$NODE_FILE

# Finally set additional PATHs and export it. We do this last, as we
# probably got some additional PATHs from the includes.
export PATH="$HOME/bin:$PATH";

# Load RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Finally, export our shell prompt & prompt command
export PS1
export PROMPT_COMMAND

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
